name: 'build and deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - mainx

env:
  DOTNET_VERSION: '7.x'
  PROJECT_FILE: ${{ github.workspace }}/KenByrd.TestFuncs/KenByrd.TestFuncs.csproj
  OUTPUT_FOLDER: ${{ github.workspace }}/output
  ARTIFACT_NAME: ${{github.ref_name}}-${{ github.run_number }}
        
jobs:
  build:
    name: 'build'
    runs-on: 'ubuntu-latest'
    steps:
      uses: 'byrddroppings/test/build@main'
      with:
        DOTNET_VERSION: env.DOTNET_VERSION
        PROJECT_FILE: env.PROJECT_FILE
        ARTIFACT_NAME: env.ARTIFACT_NAME
      