name: 'build'

on:
  workflow_dispatch:
  push:
    branches:
      - mainx

env:
  DOTNET_VERSION: '7.x'
  PROJECT_FILE: ${{ github.workspace }}/KenByrd.TestFuncs/KenByrd.TestFuncs.csproj
  OUTPUT_FOLDER: ${{ github.workspace }}/output
  ARTIFACT_NAME: ${{github.ref_name}}-${{ github.run_number }}
        
jobs:
  build:
    name: 'build'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'install dotnet ${{ env.DOTNET_VERSION }}'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '${{ env.DOTNET_VERSION }}'

      - name: 'download ${{ github.repository }} (${{ github.ref_name }})'
        uses: actions/checkout@v3

      - name: 'build'
        run: 'dotnet build --configuration Release --output ${{ env.OUTPUT_FOLDER }} ${{ env.PROJECT_FILE }}'

      - name: 'upload'
        uses: actions/upload-artifact@v3
        with:
          name: '${{ env.ARTIFACT_NAME }}'
          path: '${{ env.OUTPUT_FOLDER }}'
