name: 'build'

on:
  push:
    branches:
      - main

env:
  runner: 'ubuntu-latest'
  dotnet-version: '7.x'

jobs:
  build:
    runs-on: ${{ env.runer }}
    steps:
      run: echo '${{ env.dotnet-version }}'


  