name: 'build'

on:
  workflow_call:    
    inputs:
      DOTNET_VERSION:
        type: string
        required: true
        
      PROJECT_FILE:
        type: string
        required: true
        
      ARTIFACT_NAME:
        type: string
        required: true
    
env:
  OUTPUT_FOLDER: ${{ github.workspace }}/output

runs:
  using: "composite"
  steps:
    - name: 'install dotnet ${{ inputs.DOTNET_VERSION }}'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '${{ inputs.DOTNET_VERSION }}'

    - name: 'checkout ${{ github.repository }} (${{ github.ref_name }})'
      uses: actions/checkout@v3

    - name: 'build'
      run: 'dotnet build --configuration Release --output ${{ env.OUTPUT_FOLDER }} ${{ inputs.PROJECT_FILE }}'

    - name: 'upload'
      uses: actions/upload-artifact@v3
      if: ${{ false }}
      with:
        name: '${{ env.ARTIFACT_NAME }}'
        path: '${{ env.OUTPUT_FOLDER }}'
    
    