name: build

on:
  push:
    branches:
      - main

  release:

env:
  dotnet-version: '7.x'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - run: echo '${{ env.dotnet-version }}'


  