name: caller

on:
  workflow_dispatch:
    
env:
  dotnet_version: '7.x'
    
jobs:
    ready:
      runs-on: 'ubuntu-latest'
      steps:
        - run: echo "I'm ready"
          
    setup:
      runs-on: 'ubuntu-latest'
      outputs:
        dotnet-version: ${{ steps.set.output.dotnet-version }}
      steps:
        - id: set
          run: echo "dotnet-version=${{ env.dotnet-version }}" >> GITHUB_OUTPUT

    echo:
      runs-on: 'ubuntu-latest'
      steps:
        - run: echo "DOTNET VERSION ${{ needs.setup.output.dotnet-version }}"
    
    call:      
      uses: ./.github/workflows/callee.yaml
      with:
        dotnet-version: ${{ needs.setup.outputs.dotnet_version }}
      
      