name: caller

on:
  workflow_dispatch:
    
env:
  dotnet-version: '7.x'
    
jobs:
    ready:
      runs-on: 'ubuntu-latest'
      steps:
        - run: echo ${{ env.dotnet-version }}
        - run: echo $${{ vars.dotnet-version }}
          
          
