name: caller

on:
  workflow_dispatch:
    
env:
  dotnet_version: '7.x'
    
jobs:
    ready:
      runs-on: 'ubuntu-latest'
      steps:
        - run: echo "I'm ready"
    
    call:      
      uses: ./.github/workflows/callee.yaml
      with:
        dotnet-version: ${{ env.dotnet_version }}
      
      