name: caller

on:
  workflow_dispatch:
    
jobs:
    ready:
      runs-on: 'ubuntu-latest'
      steps:
        - run: echo "I'm ready"
    
    call:      
      uses: ./.github/workflows/callee.yaml
      
      