name: 'deploy'

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        
jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
      - run: echo '${{ toJSON(inputs) }}'

