name: 'test'

on:
  push:
    branches: 
      - main
      
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - playground
          - test
          - sandbox
          - production

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - if: ${{ github.event_name }} == 'workflow_dispatch'
        run: echo "environment=${{ inputs.environment }}" >> $GITHUB_ENV
      
      - if: ${{ github.event_name }} != 'workflow_dispatch'
        run: echo "environment=playground" >> $GITHUB_ENV
            
      - run: echo 'environment = ${{ env.environment }}'