name: 'test'

on:
  push:
    branches: 
      - main
      
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - playground
          - staging

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.setup-step.outputs.environment }}
    steps:
      - if: github.event_name == 'workflow_dispatch'
        run: echo "environment=${{ inputs.environment }}" >> $GITHUB_ENV
      
      - if: github.event_name != 'workflow_dispatch'
        run: echo "environment=playground" >> $GITHUB_ENV
        
      - id: setup-step
        run: echo "environment=${{ env.environment }}" >> $GITHUB_OUTPUT
                
      - run: echo "environment = ${{ steps.setup-step.outputs.environment }}"
        
      - run: echo "${{ toJSON(steps) }}"

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: 'echo "deploying to environment: ${{ needs.setup.outputs.environment }}"'
        
  test:
    runs-on: ubuntu-latest
    needs: setup
    environment: ${{ needs.setup.outputs.environment }}
    steps:
      - run: 'echo "running tests against environment: ${{ needs.setup.outputs.environment }}"'
      - run: 'echo my_secret = ${{ secrets.my_secret }}'
      - run: 'echo my_variable = ${{ vars.my_variable }}'