name: 'test'

on:
  push:
    branches: 
      - main
      
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - playground
          - test
          - sandbox
          - production

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.environment }}
    steps:
      - if: github.event_name == 'workflow_dispatch'
        run: echo "environment=${{ inputs.environment }}" >> $GITHUB_ENV
      
      - if: github.event_name != 'workflow_dispatch'
        run: echo "environment=playground" >> $GITHUB_ENV
        
      - name: set-environment
        run: echo "environment=whassup" >> $GITHUB_OUTPUT
                
      - run: echo "output environment = ${{ steps.set-environment.outputs.environment }}"
            
      - run: echo 'environment = ${{ env.environment }}'

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: 'echo "environment: ${{ needs.setup.outputs.environment }}"'
        
        