name: 'test'

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - playground
          - test
          - staging

jobs:    
  setup:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.setup-step.outputs.environment }}
    steps:
      - if: github.event_name == 'workflow_dispatch'
        run: echo "environment=${{ inputs.environment }}" >> $GITHUB_ENV
      
      - if: github.event_name != 'workflow_dispatch'
        run: echo "environment=playground" >> $GITHUB_ENV
        
      - id: setup-step
        run: echo "environment=${{ env.environment }}" >> $GITHUB_OUTPUT
                
      - run: echo "environment = ${{ steps.setup-step.outputs.environment }}"
        
      - run: echo "${{ toJSON(steps) }}"

  deploy:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        environment: ${{ fromJson(needs.setup.outputs.environments) }}
    steps:
      - run: 'echo "deploying to environment: ${{ matrix.environment }}"'
